{{- if .Values.vault.server.authDelegator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-server-token-review
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: etx-vault
    app.kubernetes.io/component: auth-delegator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: etx-vault
    namespace: {{ .Values.namespace }}
{{- end }}
