apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault-etx-lab
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: etx-lab-infrastructure
    demo.redhat.com/platform: "true"
  annotations:
    description: "HashiCorp Vault - ETX Lab secrets management"