{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: etx-keycloak
    app.kubernetes.io/instance: etx-keycloak
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: etx-lab-infrastructure
    demo.redhat.com/infra: "true"
  annotations:
    description: "ETX Lab Keycloak - isolated from cluster's default SSO"
{{- end }}